# Copyright 2025  AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: v1
managed:
  enabled: true
plugins:
  - name: openapiv2
    out: ./generated/openapi/
