# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

default_stages: [pre-commit, pre-push]
exclude: (sdk/python/agntcy/.*)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files # Prevent giant files from being committed
  - id: detect-private-key      # Checks for the existence of private keys
  - id: check-case-conflict     # Check for files with names that would conflict on a case-insensitive filesystem
  - id: check-merge-conflict    # Check for files that contain merge conflict strings
  - id: check-symlinks          # Checks for symlinks which do not point to anything
  - id: end-of-file-fixer       # Makes sure files end in a newline and only a newline
  - id: mixed-line-ending       # Replaces or checks mixed line ending
  - id: trailing-whitespace     # Trims trailing whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.9
  hooks:
    - id: ruff
      args: [--fix]
      types_or: [ python, pyi, jupyter ]
      files: agntcyiden
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/srstevenson/nb-clean
  rev: 3.3.0
  hooks:
    - id: nb-clean
      args: [--remove-empty-cells]
