# Copyright 2025 AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Release the Issuer CLI and the Node Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

# Declare write permissions
permissions:
  contents: 'write'
  packages: 'write'
  attestations: 'read'

jobs:
  pre-release-test:
    name: Pre Release Test
    uses: ./.github/workflows/reusable-test.yml

  prepare-release:
    name: Prepare Release
    needs: [pre-release-test]
    outputs:
      version: ${{ steps.set-version.outputs.version }}
      targets: ${{ steps.all-targets.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set version
        id: set-version
        run: echo "version=$(echo "$GITHUB_REF" | cut -d / -f 3 | cut -c2-)" >> "$GITHUB_OUTPUT"

      - name: List all targets
        id: all-targets
        uses: docker/bake-action/subaction/list-targets@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
          workdir: ./deployments/docker
          target: default
        continue-on-error: true

  build-and-push-all-images:
    name: Build and Push Docker Images
    uses: ./.github/workflows/reusable-docker.yml
    needs: [prepare-release]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.prepare-release.outputs.targets) }}
    with:
      bake-targets: ${{ matrix.target }}
      image-tag: ${{ needs.prepare-release.outputs.version }}
      image-repo: ghcr.io/${{ github.repository }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-issuer-client:
    name: Build and Release Issuer Cli
    uses: ./.github/workflows/reusable-go.yml
    needs: [prepare-release]
    with:
      workdir: ./cmd/issuer
      config: ../../.github/configs/issuer-cli-goreleaser.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

  publish-helm-charts:
    uses: ./.github/workflows/reusable-helm.yml
    needs: [prepare-release]
    with:
      charts-dir: "charts"
      gh-pages-branch: "gh-pages"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  build-python-sdk:
    name: Build Python SDK
    needs: [prepare-release]
    uses: ./.github/workflows/reusable-python.yml

  publish-python-sdk:
    name: Upload Identity Python Package to PyPI
    runs-on: ubuntu-latest
    needs:
      - build-python-sdk
    if: |
      always() &&
      (needs.build-python-sdk.result == 'skipped' || needs.build-python-sdk.result == 'success')
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true
          path: ./dist

      - name: Show files
        run: ls -l ./dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ./dist
