# Copyright 2025 Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: Reusable Python Build

on:
  workflow_call:

jobs:
  python-bindings-wheels:
    runs-on: ${{ matrix.platform.runner }}
    defaults:
      run:
        shell: bash
        working-directory: ./
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            os: linux
            target: x86_64
          - runner: windows-latest
            os: windows
            target: x64
          - runner: macos-13 # We use macos-13 as it is a x86_64 runner
            os: macos
            target: x86_64
          - runner: macos-15
            os: macos
            target: aarch64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: ./.github/actions/setup-python
        with:
          py-install: false
          poetry-install: false
          uv-install: true
      - name: Build wheel
        run: |
          uv build
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.platform.os }}-${{ matrix.platform.target }}
          path: ./dist
